kind: pipeline
type: docker
name: build
platform:
  os: linux
  arch: amd64
steps:
  - name: build
    image: docker
    commands:
      - docker build -t cc99 .
    volumes:
      - name: cache
        path: /var/run/docker.sock
trigger:
  branch:
    - main
  event:
    - push
    - rollback
volumes:
  - name: cache
    host:
      path: /var/run/docker.sock
---
kind: pipeline
type: exec
name: deploy
platform:
  os: linux
  arch: amd64
clone:
  disable: true
steps:
  - name: deploy
    commands:
      - echo hello
      - cd /app/cc99
      - docker-compose up -d
      - docker image prune -f
      - docker cp cc99-app-1:/srv/cc99 /srv/
      - nginx -s reload
depends_on:
  - build
