name: release

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install minimal stable
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "13.0"
        directory: ${{ runner.temp }}/llvm

    - name: build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release

    - name: release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          ./target/release/cc99
